### ISSUE TITLE
Move APP or sync data to External SD Card

### ISSUE THREAD

**Issue by jamesmanning** [Trellmor/BerryMotesApp#2]
(filing on behalf of @QuillOmega0 as a copy of https://github.com/berrycardsagainsthumanity/berrymotes/issues/46 )

How possible would it to be to allow moving the APP or setting it to sync the emotes to a custom location (e.g. an external SD card)

**Comment by Trellmor** [comment]
Development has moved to https://github.com/BTDev/BerrymotesAndroid
