### ISSUE TITLE
Please add some kind of UI to show current stats

### ISSUE THREAD

**Issue by jamesmanning** [Trellmor/BerryMotesApp#3]
I may just be missing it, but was kind of hoping for a simple stats of what's currently synced. Number of emotes and number of subreddits would be great, and if space and existing data structures allowed, maybe:

12,345 emotes
13,765 names
156 subreddits
4,321 nsfw
2,875 animated
 (Probably other useful groupings I'm blanking on)

Maybe a "Sync Stats" menu item in the existing 3-dot menu that has Info/Sync/Settings?

**Comment by Trellmor** [comment]
Development has moved to https://github.com/BTDev/BerrymotesAndroid
